javax:
  persistance:
    jdbc:
      driver: org.h2.Driver

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    root: INFO
    com.shelach: DEBUG
server:
  tomcat:
    access-log-enabled: true
    access-log-pattern: "%h %l %u %t %r %s %b %D"
comax:
  api:
    items-url: http://ws.comax.co.il/Comax_WebServices/Items_Service.asmx
shelach:
  use-proxy: false
  proxy-port: 8888 #default fiddler port

